apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: monitoring
  sources:
    # Source 1: Helm chart Velero
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 7.2.0
      helm:
        releaseName: velero
        valueFiles:
          - $values/apps/velero/values-prod.yaml
    # Source 2: Repo Git contenant les values et le secret (CORRIGÉ EN HTTPS)
    - repoURL: https://github.com/MathisBrb/app-argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
