apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: velero
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2024-06-12T14-34-03Z
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set myminio http://minio.velero.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                echo "Waiting for MinIO..."
                sleep 5
              done
              mc mb --ignore-existing myminio/velero
              echo "Bucket 'velero' created successfully"
          envFrom:
            - secretRef:
                name: minio-credentials
