apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: velero
  annotations:
    # Change cette valeur pour forcer ArgoCD à recréer le Job (spec.template est immutable)
    triforce.dev/recreate: "2026-02-05-1602"
spec:
  backoffLimit: 5
  # Certaines versions/serveurs exigent des labels + selector explicites.
  selector:
    matchLabels:
      job-name: minio-create-bucket
  template:
    metadata:
      labels:
        job-name: minio-create-bucket
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "minio-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/minio"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/minio" -}}
          export MINIO_ROOT_USER="{{ .Data.data.rootUser }}"
          export MINIO_ROOT_PASSWORD="{{ .Data.data.rootPassword }}"
          {{- end -}}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2024-06-12T14-34-03Z
          command:
            - /bin/sh
            - -c
            - |
              set -e
              source /vault/secrets/config
              until mc alias set myminio http://minio.velero.svc.cluster.local:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "Waiting for MinIO..."
                sleep 5
              done
              mc mb --ignore-existing myminio/velero
              echo "Bucket 'velero' created successfully"
