---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # ===== A MODIFIER =====
    server: "10.202.0.206"       # Ex: 192.168.1.100
    path: "/srv/nfs/minio"       # Ex: /export/backups/velero
    # ======================
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: velero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: minio-nfs-pv
  storageClassName: ""
