apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 10Gi # Ou plus selon la place sur ton CentOS
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs: # <--- C'est ici qu'on branche le CentOS
    path: /var/nfs/minio-data
    server: 10.202.22.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: velero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: minio-nfs-pv # On force le lien avec le PV ci-dessus
  storageClassName: "" # Important pour éviter que le provisionneur par défaut ne s'en mêle
